/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pluginsproject

import org.gradle.api.Plugin
import org.gradle.api.Project

class PluginsProjectPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.apply {
            plugins {
                kotlin("jvm") version "1.9.21"
                id("org.jlleitschuh.gradle.ktlint") version "12.1.0"
            }

            repositories {
                mavenCentral()
            }

            dependencies {
                testImplementation("org.jetbrains.kotlin:kotlin-test")
            }

            tasks.test {
                useJUnitPlatform()
            }

            kotlin {
                jvmToolchain(21)
            }
        }
    }
}
