name: Continuous Deployment

on:
  push:
    branches:
      - master
      - interpreter
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ env.PUBLISH_USER }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}